---
- hosts: all
#  sudo: yes

####write rules for install rpm
  tasks:
     - yum: name=https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
####「 - name:」はansible動作中の「TASK」の横に表示されます
####「yum:」後にインストールしたいソフトウェアを記述

     - name:  vimをinstallしています
       yum: name=vim

####yumは一行で書く事も可能。ソフトウェアひとつにつき一行
####stateは省略可能。その他にもオプションはあります。ググってみて下さい

     - yum: name=zabbix-server-mysql state=latest
     - yum: name=zabbix-web-mysql
     - yum: name=zabbix-agent
     - yum: name=mariadb
     - yum: name=mariadb-server
#     - yum: name=python-pip           

####ファイルの編集(SELINUXの書き換え)
     - name: modify a file(SELINUXの書き換え)
       replace:
         dest: /etc/sysconfig/selinux
         regexp: 'SELINUX=enforcing'
         replace: 'SELINUX=disabled'
#ファイルの書き換え方法は複数あります。
#これがわかやすいと思う。。「regexp」は正規表現の意味

####後から知ったのですがlibselinux-pythonモジュールを使えば
####SELinuxの操作自体ansibleでできました。。

###libselinux-pythonをyumでインストール
     - name: Install libselinux-python
       yum: name=libselinux-python state=present

###SElinuxの設定をdisabledへ変更
#     - name: SELinuxのDisable設定
#       selinux: state=enforcing

#サービスの起動設定など
#    - service: name=httpd state=started enabled=yes

     - service: name=mariadb state=started enabled=yes
     - service: name=zabbix-server state=started enabled=yes

###下の書き方でもOK
     - service:
         name: httpd
         state: started

####無理やりmariadb設定
###コマンド入力
##     - name: mysql_secure_installation
##       shell: "mysql_secure_installation"

###プロンプト待ち
##     - name: プロンプトを待つ
##       pause: prompt="Enter current password for root (enter for none):"

#     - name: "mysql_secure_installation"
 #      expect:
  #       command /usr/bin/mysql_secure_installation
   #      responses:
    #       "Enter current password for root \\(enter for none\\): " : ""
     #      "Set root password\\? \\[Y\\/n\\] " : "Y"
      #     "New password: " : "{{Root123!}}"
       #    "Re-enter new password: " : "{{Root123!}}"
        #   "Remove anonymous users\\?" : "y"
         #  "Disallow root login remotely\\?" : "y"
          # "Remove test database and access to it\\?" : "y"
          # "Reload privilege tables now\\?" : "y"

     - name: mysql_secure_installation Command Test
       expect:
         command: mysql_secure_installation
         responses:
           'Enter current password for root (enter for none):': "\n"
           'Set root password? [Y/n]:': 'y'
           'New password:': 'Root123!'
           'Re-enter new password:': 'Root123!'
           'Remove anonymous users? [Y/n]:': 'y'
           'Disallow root login remotely? [Y/n]:': 'y'
           'Remove test database and access to it? [Y/n]:': 'y'
           'Reload privilege tables now? [Y/n]:': 'y'

         echo: yes
